### ISSUE TITLE
Feature request: custom sort function to the FileList class

### ISSUE THREAD

**Issue by krishna-esrlabs** [AEV/nucleus7#4]
## Actual Behavior
In the **FileList** class, at the moment the files are sorted according to the first subset key
```
    @object_utils.assert_is_built
    def sort(self) -> "FileList":
        """
        Sort the file names using self.sort_fn

        It will sort the first key in according to sort_fn and then will select
        other keys according to sorted indices

        Returns
        -------
        self
            self for chaining
        """
        first_subset_key, first_subset = _get_first_key_and_subset(
            self._file_names)
        sorted_indices, _ = zip(
            *sorted(enumerate(first_subset),
                    key=lambda x: self.sort_fn(x[1], key=first_subset_key)))
        file_names_sorted = {
            each_key: [each_list[ind_sorted] for ind_sorted in sorted_indices]
            for each_key, each_list in self._file_names.items()}
        self._file_names = file_names_sorted
        return self
```

## Expected Behavior
The naming convention varies for different datasets. Depending on the naming convention the respective sorting function may be required. A possible idea can be, to keep a list of sort functions in a file and specify the function name in the json file on demand.

**Comment by OleksandrVorobiov** [comment]
The reason that only first subkey is used is that it does not matter which one to use. First the file names will be matched according to the pattern and then they will be sorted according to the same pattern, so no matter which subkey to use.
From my point of view, it is much better and more explicit to have the a new FileList implementation for each sorting function as for now.
Other more generic way would be to extract the sorting from FileList and inject whatever sorting you need (like it is done with LearningRateManipulator).

**Comment by krishna-esrlabs** [comment]
@OleksandrVorobiov I agree, it's easier to make a new FileList class and override the sort function. So I am closing the issue. But in future if there exists many FileList class implementations just for the sake of different sorting functions, I will reopen this feature request and let's go for the other solution you mentioned. Thanks!
